### ISSUE TITLE
Redirect petitions to forums

### ISSUE THREAD

**Issue by timbocode** [ClassicPress/redirect-petitions#1]
Not sure if this repo is still active or if this is the right place for this but one way of redirecting all petitions to the corresponding petition on the forums is by using  the following rule in `.htaccess`:

`RewriteRule ^posts/\d+/(.*)$ https://forums.classicpress.net/t/$1 [L,R=301]`

As an example, this would redirect https://petitions.classicpress.net/posts/218/better-database-maintenance to https://forums.classicpress.net/t/better-database-maintenance.

**Comment by nylen** [comment]
There are some petitions that don't map exactly to the same slug on the forums due to different handling of characters like `_` and `&` in titles. Here is the full mapping: https://github.com/ClassicPress/subdomain-petitions/blob/master/urls.json

This repository would perhaps be better named `redirect-vote` - it is served from `vote.classicpress.net` because at one point that was where our petitions site was located, and it just sends all requests from `vote.classicpress.net` to `petitions.classicpress.net`. We may not even need that redirect anymore but it is not doing any harm either.

I've deployed https://github.com/ClassicPress/subdomain-petitions to petitions.classicpress.net so this issue is effectively fixed now.
